version: '3.1'

networks:
  spring:

services:
  db-order:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=order
    volumes:
      - ./init-gunmarketx.sql:/docker-entrypoint-initdb.d/init-gunmarketx.sql
    ports:
      - 35432:5432


