### Set order to publish
PATCH http://localhost:8083/api/v1/order/publish/5
Content-Type: application/json

### Set order back to draft
PATCH http://localhost:8083/api/v1/order/draft/5
Content-Type: application/json

### Set order to in_progress
PATCH http://localhost:8083/api/v1/order/inProgress
Content-Type: application/json

{
  "orderId": 6,
  "name": "I need to fix my air conditioner, so much, Plz",
  "specialistId": 2
}

### Set order to closed
PATCH http://localhost:8083/api/v1/order/close/5
Content-Type: application/json

### Set order to resolved
PATCH http://localhost:8083/api/v1/order/resolve/5
Content-Type: application/json