### Create order
POST http://localhost:8083/api/v1/order/
Content-Type: application/json

{
  "name": "I need your help so much, so so",
  "orderStatus": "DRAFT",
  "customerId": 5,
  "category": "Air conditioning master",
  "description": "I need to fix my air conditioner, so much"
}

### Create order
POST http://localhost:8083/api/v1/order/order
Content-Type: application/json

{
  "name": "English IELTS preparation",
  "orderStatus": "DRAFT",
  "customerId": 2,
  "category": "English tutor",
  "description": "I need to learn specific english for prepare to IELTS exam"
}

### Create order local
POST http://localhost:38083/api/v1/order/order
Content-Type: application/json

{
  "name": "Fix my conditioner",
  "orderStatus": "DRAFT",
  "customerId": 1,
  "category": "Air conditioning master",
  "description": "I need to fix my air conditioner, there is 39 at the street"
}

### Create order local
POST http://localhost:38083/api/v1/order/order
Content-Type: application/json

{
  "name": "English IELTS preparation",
  "orderStatus": "DRAFT",
  "customerId": 2,
  "category": "English tutor",
  "description": "I need to learn specific english for prepare to IELTS exam"
}

