server:
  port: 8080

spring:
  application:
    name: order
  datasource:
    username: nbkftggqxzkttm
    password: f8de73cbd4e8818f167f7ff086b07718c8daf636951c651942987eb4455f9f14
    url: jdbc:postgresql://ec2-52-19-188-149.eu-west-1.compute.amazonaws.com:5432/dbjtieev5doea0
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
  boot:
    admin:
      client:
        url: http://spring-admin:8085
  zipkin:
    base-url: http://zipkin:9411

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: profi.log

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
