spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:35432/order
  boot:
    admin:
      client:
        url: http://localhost:8085
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
