server:
  port: 38080
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:35432/order
  boot:
    admin:
      client:
        url: http://localhost:38085
  zipkin:
    base-url: http://localhost:39411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:38761/eureka
  instance:
    prefer-ip-address: true
