server:
  port: 38083
spring:
  zipkin:
    base-url: http://localhost:39411
  boot:
    admin:
      client:
        url: http://localhost:38085
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:38080
          predicates:
            - Path=/api/v1/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:38761/eureka
