server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
