server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  boot:
    admin:
      client:
        url: http://spring-admin:8085
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: profi.log

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
