version: '3.1'

networks:
  spring:

services:
  db-order:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=order
    volumes:
      - ./init-gunmarketx.sql:/docker-entrypoint-initdb.d/init-gunmarketx.sql
    ports:
      - 35432:5432
    networks:
      - spring

  zipkin-local:
    image: openzipkin/zipkin
    container_name: zipkin-local
    ports:
      - "39411:9411"
    networks:
      - spring

  eureka-server-local:
    image: profidocker/eureka-server:1.0
    container_name: eureka-server-local
    ports:
      - "38761:8761"
    depends_on:
      - zipkin-local
    networks:
      - spring

  spring-admin-local:
    image: profidocker/spring-admin:1.0
    container_name: spring-admin-local
    ports:
      - "38085:8085"
    depends_on:
      - zipkin-local
      - eureka-server-local
    networks:
      - spring
