INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Tutor','Tutor',null,null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('English tutor','Tutor','English',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Serbian tutor','Tutor','Serbian',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Russian tutor','Tutor','Russian',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Arabic tutor','Tutor','Arabic',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Spanish tutor','Tutor','Spanish',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('German tutor','Tutor','German',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('French tutor','Tutor','French',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Macedonian tutor','Tutor','Macedonian',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Acting','Tutor','Acting',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Biology tutor','Tutor','Biology',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Accounting tutor','Tutor','Accounting',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Geography tutor','Tutor','Geography',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Graphic design tutor','Tutor','Graphic design',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Interior design tutor','Tutor','Interior design',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Journalism tutor','Tutor','Journalism tutor',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Art tutor','Tutor','Art',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Engineering tutor','Tutor','Engineering',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Games tutor','Tutor','Games',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Computer science tutor','Tutor','Computer science',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('History tutor','Tutor','History',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Literature tutor','Tutor','Literature',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Speech therapist','Tutor','Speech therapists',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Marketing tutor','Tutor','Marketing',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Math tutor','Tutor','Math',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Medicine tutor','Tutor','Medicine',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Management tutor','Tutor','Management',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Music tutor','Tutor','Music',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Primary school tutor','Tutor','Primary school',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Social science tutor','Tutor','Social science',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Pedagogy tutor','Tutor','Pedagogy',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Layer tutor','Tutor','Layer',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Programming tutor','Tutor','Programming',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Programming mentor','Tutor','Programming mentor',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Psychology tutor','Tutor','Psychology',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Handmade tutor','Tutor','Handmade',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Physics tutor','Tutor','Physics',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Philosophy tutor','Tutor','Philosophy',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Chemistry tutor','Tutor','Chemistry',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Drawing tutor','Tutor','Drawing',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Economy tutor','Tutor','Economy',null);

INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Repair master','Repair master',null,null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Appliances repair master','Repair master','Appliances',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Landscaping master','Repair master','Landscaping',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Household appliances master','Repair master','Household appliances',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Air conditioning master','Repair master','Air conditioning',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Wall construction master','Repair master','Wall construction',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Garbage removal master','Repair master','Garbage removal',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('High-altitude work master','Repair master','High-altitude work',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Doors master','Repair master','Doors',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Dismantling of structures master','Repair master','Dismantling of structures',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Advertising production master','Repair master','Advertising production',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Engineering survey master','Repair master','Engineering survey',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Complex repair master','Repair master','Complex repair',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Computers master','Repair master','Computers',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Roofing master','Repair master','Roofing',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Blacksmith master','Repair master','Blacksmith craft',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Stairs master','Repair master','stairs',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Painting and plastering master','Repair master','Painting and plastering',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Furniture master','Repair master','Furniture',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Minor repairs master','Repair master','Minor repairs',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Metal structures master','Repair master','Metal structures',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Window master','Repair master','Window',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Finishing work master','Repair master','Finishing work',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Heating master','Repair master','Heating',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Tilers master','Repair master','Tilers',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Carpentry master','Repair master','Carpentry',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Wallpapering master','Repair master','Wallpapering',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Floors master','Repair master','Floors',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Ceilings master','Repair master','Ceilings',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Engineering and design master','Repair master','Engineering and design',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Auto repair master','Repair master','Auto repair',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Repair of water transport master','Repair master','Repair of water transport',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Repair of medical equipment master','Repair master','Repair of medical equipment',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Repair of musical instruments master','Repair master','Repair of musical instruments',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Repair of garden equipment master','Repair master','Repair of garden equipment',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Sports equipment repair master','Repair master','Sports equipment repair',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Construction Equipment Repair master','Repair master','Construction Equipment Repair',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Watch repair master','Repair master','Watch repair',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Sanitary and epidemiological master','Repair master','Sanitary and epidemiological services',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Plumbing master','Repair master','Plumbing',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Glass master','Repair master','Glass work',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Construction master','Repair master','Construction',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Turning master','Repair master','Turning works',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Facade master','Repair master','Facade works',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Electrician master','Repair master','Electrician',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Electronics master','Repair master','Electronics',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Jewelry master','Repair master','Jewelry work',null);
