INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (1, 'Tutor', null, 'Tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (2, 'Tutor', 'English', 'English tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (3, 'Tutor', 'Serbian', 'Serbian tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (4, 'Tutor', 'Russian', 'Russian tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (5, 'Tutor', 'Arabic', 'Arabic tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (6, 'Tutor', 'Spanish', 'Spanish tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (7, 'Tutor', 'German', 'German tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (8, 'Tutor', 'French', 'French tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (9, 'Tutor', 'Macedonian', 'Macedonian tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (10, 'Tutor', 'Acting', 'Acting', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (11, 'Tutor', 'Biology', 'Biology tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (12, 'Tutor', 'Accounting', 'Accounting tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (13, 'Tutor', 'Geography', 'Geography tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (14, 'Tutor', 'Graphic design', 'Graphic design tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (15, 'Tutor', 'Interior design', 'Interior design tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (16, 'Tutor', 'Journalism tutor', 'Journalism tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (17, 'Tutor', 'Art', 'Art tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (18, 'Tutor', 'Engineering', 'Engineering tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (19, 'Tutor', 'Games', 'Games tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (20, 'Tutor', 'Computer science', 'Computer science tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (21, 'Tutor', 'History', 'History tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (22, 'Tutor', 'Literature', 'Literature tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (23, 'Tutor', 'Speech therapists', 'Speech therapist', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (24, 'Tutor', 'Marketing', 'Marketing tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (25, 'Tutor', 'Math', 'Math tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (26, 'Tutor', 'Medicine', 'Medicine tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (27, 'Tutor', 'Management', 'Management tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (28, 'Tutor', 'Music', 'Music tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (29, 'Tutor', 'Primary school', 'Primary school tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (30, 'Tutor', 'Social science', 'Social science tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (31, 'Tutor', 'Pedagogy', 'Pedagogy tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (32, 'Tutor', 'Layer', 'Layer tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (33, 'Tutor', 'Programming', 'Programming tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (34, 'Tutor', 'Programming mentor', 'Programming mentor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (35, 'Tutor', 'Psychology', 'Psychology tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (36, 'Tutor', 'Handmade', 'Handmade tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (37, 'Tutor', 'Physics', 'Physics tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (38, 'Tutor', 'Philosophy', 'Philosophy tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (39, 'Tutor', 'Chemistry', 'Chemistry tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (40, 'Tutor', 'Drawing', 'Drawing tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (41, 'Tutor', 'Economy', 'Economy tutor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (42, 'Repair master', null, 'Repair master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (43, 'Repair master', 'Appliances', 'Appliances repair master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (44, 'Repair master', 'Landscaping', 'Landscaping master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (45, 'Repair master', 'Household appliances', 'Household appliances master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (46, 'Repair master', 'Air conditioning', 'Air conditioning master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (47, 'Repair master', 'Wall construction', 'Wall construction master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (48, 'Repair master', 'Garbage removal', 'Garbage removal master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (49, 'Repair master', 'High-altitude work', 'High-altitude work master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (50, 'Repair master', 'Doors', 'Doors master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (51, 'Repair master', 'Dismantling of structures', 'Dismantling of structures master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (52, 'Repair master', 'Advertising production', 'Advertising production master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (53, 'Repair master', 'Engineering survey', 'Engineering survey master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (54, 'Repair master', 'Complex repair', 'Complex repair master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (55, 'Repair master', 'Computers', 'Computers master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (56, 'Repair master', 'Roofing', 'Roofing master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (57, 'Repair master', 'Blacksmith craft', 'Blacksmith master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (58, 'Repair master', 'stairs', 'Stairs master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (59, 'Repair master', 'Painting and plastering', 'Painting and plastering master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (60, 'Repair master', 'Furniture', 'Furniture master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (61, 'Repair master', 'Minor repairs', 'Minor repairs master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (62, 'Repair master', 'Metal structures', 'Metal structures master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (63, 'Repair master', 'Window', 'Window master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (64, 'Repair master', 'Finishing work', 'Finishing work master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (65, 'Repair master', 'Heating', 'Heating master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (66, 'Repair master', 'Tilers', 'Tilers master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (67, 'Repair master', 'Carpentry', 'Carpentry master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (68, 'Repair master', 'Wallpapering', 'Wallpapering master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (69, 'Repair master', 'Floors', 'Floors master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (70, 'Repair master', 'Ceilings', 'Ceilings master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (71, 'Repair master', 'Engineering and design', 'Engineering and design master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (72, 'Repair master', 'Auto repair', 'Auto repair master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (73, 'Repair master', 'Repair of water transport', 'Repair of water transport master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (74, 'Repair master', 'Repair of medical equipment', 'Repair of medical equipment master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (75, 'Repair master', 'Repair of musical instruments', 'Repair of musical instruments master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (76, 'Repair master', 'Repair of garden equipment', 'Repair of garden equipment master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (77, 'Repair master', 'Sports equipment repair', 'Sports equipment repair master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (78, 'Repair master', 'Construction Equipment Repair', 'Construction Equipment Repair master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (79, 'Repair master', 'Watch repair', 'Watch repair master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (80, 'Repair master', 'Sanitary and epidemiological services', 'Sanitary and epidemiological master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (81, 'Repair master', 'Plumbing', 'Plumbing master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (82, 'Repair master', 'Glass work', 'Glass master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (83, 'Repair master', 'Construction', 'Construction master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (84, 'Repair master', 'Turning works', 'Turning master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (85, 'Repair master', 'Facade works', 'Facade master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (86, 'Repair master', 'Electrician', 'Electrician master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (87, 'Repair master', 'Electronics', 'Electronics master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (88, 'Repair master', 'Jewelry work', 'Jewelry master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (89, 'Beauty master', null, 'Beauty master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (90, 'Beauty master', 'Makeup', 'Makeup master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (91, 'Beauty master', 'Manicure', 'Manicure master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (92, 'Beauty master', 'Hairstyles', 'Hairstyles master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (93, 'Beauty master', 'Epilation', 'Epilation master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (94, 'Beauty master', 'Stylist', 'Stylist master', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (95, 'Freelancer', null, 'Freelancer', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (96, 'Freelancer', 'Designer', 'Designer', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (97, 'Freelancer', 'Marketing', 'Marketing', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (98, 'Freelancer', 'Sys Admin', 'Sys Admin', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (99, 'Freelancer', 'Translator', 'Translator', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (100, 'Autoinstructor', null, 'Autoinstructor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (101, 'Autoinstructor', 'Driving manual auto', 'Driving manual autoinstructor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (102, 'Autoinstructor', 'Driving auto auto', 'Driving auto autoinstructor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (103, 'Autoinstructor', 'Motorcycle', 'Motorcycle autoinstructor', null);
INSERT INTO public.category (category_id, first_level, second_level, show_name, third_level) VALUES (104, 'Autoinstructor', 'Emergency driving', 'Emergency driving autoinstructor', null);

INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Beauty master','Beauty master',null,null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Makeup master','Beauty master','Makeup',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Manicure master','Beauty master','Manicure',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Hairstyles master','Beauty master','Hairstyles',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Epilation master','Beauty master','Epilation',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Stylist master','Beauty master','Stylist',null);

INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Freelancer','Freelancer',null,null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Designer','Freelancer','Designer',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Marketing','Freelancer','Marketing',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Sys Admin','Freelancer','Sys Admin',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Translator','Freelancer','Translator',null);

INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Autoinstructor','Autoinstructor',null,null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Driving manual autoinstructor','Autoinstructor','Driving manual auto',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Driving auto autoinstructor','Autoinstructor','Driving auto auto',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Motorcycle autoinstructor','Autoinstructor','Motorcycle',null);
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Emergency driving autoinstructor','Autoinstructor','Emergency driving',null);
