INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('English tutor','Tutor','English','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Serbian tutor','Tutor','Serbian','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Russian tutor','Tutor','Russian','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Arabic tutor','Tutor','Arabic','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Spanish tutor','Tutor','Spanish','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('German tutor','Tutor','German','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('French tutor','Tutor','French','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Macedonian tutor','Tutor','Macedonian','');

INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Acting','Tutor','Acting','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Biology tutor','Tutor','Biology','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Accounting tutor','Tutor','Accounting','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Geography tutor','Tutor','Geography','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Graphic design tutor','Tutor','Graphic design','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Interior design tutor','Tutor','Interior design','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Journalism tutor','Tutor','Journalism tutor','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Art tutor','Tutor','Art','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Engineering tutor','Tutor','Engineering','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Games tutor','Tutor','Games','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Computer science tutor','Tutor','Computer science','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('History tutor','Tutor','History','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Literature tutor','Tutor','Literature','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Speech therapist','Tutor','Speech therapists','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Marketing tutor','Tutor','Marketing','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Math tutor','Tutor','Math','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Medicine tutor','Tutor','Medicine','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Management tutor','Tutor','Management','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Music tutor','Tutor','Music','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Primary school tutor','Tutor','Primary school','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Social science tutor','Tutor','Social science','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Pedagogy tutor','Tutor','Pedagogy','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Layer tutor','Tutor','Layer','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Programming tutor','Tutor','Programming','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Programming mentor','Tutor','Programming mentor','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Psychology tutor','Tutor','Psychology','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Handmade tutor','Tutor','Handmade','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Physics tutor','Tutor','Physics','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Philosophy tutor','Tutor','Philosophy','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Chemistry tutor','Tutor','Chemistry','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Drawing tutor','Tutor','Drawing','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Economy tutor','Tutor','Economy','');

INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Appliances repair master','Repair master','Appliances','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Landscaping master','Repair master','Landscaping','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Household appliances master','Repair master','Household appliances','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Air conditioning master','Repair master','Air conditioning','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Wall construction master','Repair master','Wall construction','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Garbage removal master','Repair master','Garbage removal','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('High-altitude work master','Repair master','High-altitude work','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Doors master','Repair master','Doors','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Dismantling of structures master','Repair master','Dismantling of structures','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Advertising production master','Repair master','Advertising production','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Engineering survey master','Repair master','Engineering survey','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Complex repair master','Repair master','Complex repair','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Computers master','Repair master','Computers','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Roofing master','Repair master','Roofing','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Blacksmith master','Repair master','Blacksmith craft','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Stairs master','Repair master','stairs','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Painting and plastering master','Repair master','Painting and plastering','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Furniture master','Repair master','Furniture','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Minor repairs master','Repair master','Minor repairs','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Metal structures master','Repair master','Metal structures','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Window master','Repair master','Window','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Finishing work master','Repair master','Finishing work','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Heating master','Repair master','Heating','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Tilers master','Repair master','Tilers','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Carpentry master','Repair master','Carpentry','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Wallpapering master','Repair master','Wallpapering','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Floors master','Repair master','Floors','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Ceilings master','Repair master','Ceilings','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Engineering and design master','Repair master','Engineering and design','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Auto repair master','Repair master','Auto repair','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Repair of water transport master','Repair master','Repair of water transport','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Repair of medical equipment master','Repair master','Repair of medical equipment','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Repair of musical instruments master','Repair master','Repair of musical instruments','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Repair of garden equipment master','Repair master','Repair of garden equipment','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Sports equipment repair master','Repair master','Sports equipment repair','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Construction Equipment Repair master','Repair master','Construction Equipment Repair','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Watch repair master','Repair master','Watch repair','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Sanitary and epidemiological master','Repair master','Sanitary and epidemiological services','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Plumbing master','Repair master','Plumbing','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Glass master','Repair master','Glass work','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Construction master','Repair master','Construction','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Turning master','Repair master','Turning works','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Facade master','Repair master','Facade works','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Electrician master','Repair master','Electrician','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Electronics master','Repair master','Electronics','');
INSERT INTO category (show_name, first_level, second_level, third_level) VALUES ('Jewelry master','Repair master','Jewelry work','');
