INSERT INTO category_question (category_id, property_name, question) VALUES (1, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (2, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (3, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (4, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (5, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (6, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (7, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (8, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (9, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (10, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (11, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (12, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (13, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (14, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (15, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (16, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (17, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (18, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (19, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (20, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (21, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (22, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (23, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (24, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (25, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (26, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (27, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (28, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (29, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (30, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (31, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (32, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (33, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (34, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (35, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (36, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (37, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (38, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (39, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (40, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (41, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (42, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (43, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (44, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (45, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (46, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (47, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (48, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (49, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (50, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (51, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (52, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (53, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (54, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (55, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (56, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (57, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (58, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (59, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (60, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (61, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (62, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (63, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (64, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (65, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (66, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (67, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (68, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (69, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (70, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (71, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (72, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (73, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (74, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (75, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (76, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (77, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (78, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (79, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (80, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (81, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (82, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (83, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (84, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (85, 'price', 'How much money u wanna to spend?');
INSERT INTO category_question (category_id, property_name, question) VALUES (86, 'price', 'How much money u wanna to spend?');

INSERT INTO category_question (category_id, property_name, question) VALUES (1,  'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (2,  'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (3,  'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (4,  'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (5,  'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (6,  'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (7,  'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (8,  'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (9,  'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (10, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (11, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (12, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (13, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (14, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (15, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (16, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (17, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (18, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (19, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (20, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (21, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (22, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (23, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (24, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (25, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (26, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (27, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (28, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (29, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (30, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (31, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (32, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (33, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (34, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (35, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (36, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (37, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (38, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (39, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (40, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (41, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (42, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (43, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (44, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (45, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (46, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (47, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (48, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (49, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (50, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (51, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (52, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (53, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (54, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (55, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (56, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (57, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (58, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (59, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (60, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (61, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (62, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (63, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (64, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (65, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (66, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (67, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (68, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (69, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (70, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (71, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (72, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (73, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (74, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (75, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (76, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (77, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (78, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (79, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (80, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (81, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (82, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (83, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (84, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (85, 'age', 'How old are u?');
INSERT INTO category_question (category_id, property_name, question) VALUES (86, 'age', 'How old are u?');
