version: '3.1'

networks:
  spring:

services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  eureka-server:
    image: profidocker/eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - zipkin
    networks:
      - spring

  apigw:
    image: profidocker/apigw:1.0
    container_name: apigw
    ports:
      - "8083:8083"
    depends_on:
      - zipkin
      - eureka-server
    networks:
      - spring

  order:
    image: profidocker/order:1.0
    container_name: order
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - eureka-server
      - apigw
    networks:
      - spring
