server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
  boot:
    admin:
      client:
        url: http://spring-admin:8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
